/** @type {import('tailwindcss').Config} */
export default {
	content: ['./src/**/*.{astro,html,js,jsx,md,mdx,svelte,ts,tsx,vue}'],
	theme: {
		extend: {
			colors: {
				"surface-container-high": "#e7e8e8",
				"primary-fixed-dim": "#a1d0c7",
				"on-tertiary": "#ffffff",
				"inverse-on-surface": "#f0f1f1",
				"surface-container-low": "#f3f4f4",
				"on-background": "#191c1c",
				"surface-variant": "#e1e3e3",
				"background": "#f8f9f9",
				"primary-fixed": "#bcece3",
				"on-primary": "#ffffff",
				"on-error": "#ffffff",
				"secondary-container": "#d2e2ec",
				"surface-container-highest": "#e1e3e3",
				"surface-tint": "#3a665f",
				"on-secondary-fixed": "#0e1d25",
				"on-surface": "#191c1c",
				"on-primary-fixed": "#00201c",
				"on-tertiary-container": "#f7fff1",
				"on-error-container": "#93000a",
				"on-tertiary-fixed": "#161d15",
				"on-secondary-container": "#55656d",
				"surface-dim": "#d9dada",
				"surface-bright": "#f8f9f9",
				"surface-container": "#edeeee",
				"on-primary-fixed-variant": "#204e47",
				"tertiary-fixed": "#dde5d8",
				"error-container": "#ffdad6",
				"inverse-primary": "#a1d0c7",
				"tertiary": "#565e54",
				"primary": "#37645d",
				"secondary-fixed-dim": "#b9c9d3",
				"on-secondary": "#ffffff",
				"on-surface-variant": "#404846",
				"on-secondary-fixed-variant": "#3a4951",
				"tertiary-container": "#6f776c",
				"tertiary-fixed-dim": "#c1c9bc",
				"secondary": "#516169",
				"outline": "#707976",
				"surface": "#f8f9f9",
				"error": "#ba1a1a",
				"primary-container": "#507d75",
				"inverse-surface": "#2e3131",
				"surface-container-lowest": "#ffffff",
				"secondary-fixed": "#d5e5ef",
				"on-primary-container": "#f4fffb",
				"on-tertiary-fixed-variant": "#41493f",
				"outline-variant": "#c0c8c5"
			},
			spacing: {
				"unit": "8px",
				"margin-desktop": "64px",
				"max-width": "1280px",
				"margin-mobile": "16px",
				"gutter": "24px"
			},
			fontFamily: {
				"display-lg": ["Comfortaa", "sans-serif"],
				"headline-lg-mobile": ["Comfortaa", "sans-serif"],
				"headline-lg": ["Comfortaa", "sans-serif"],
				"body-md": ["'Plus Jakarta Sans'", "sans-serif"],
				"label-md": ["'Plus Jakarta Sans'", "sans-serif"],
				"headline-md": ["Comfortaa", "sans-serif"],
				"body-lg": ["'Plus Jakarta Sans'", "sans-serif"],
				"label-sm": ["'Plus Jakarta Sans'", "sans-serif"]
			}
		},
	},
	plugins: [],
}
